export type LocationRegion = { name: string; cities: string[] };
export type LocationCountry = { regionLabel: string; regions: LocationRegion[] };

export const LOCATIONS: Record<string, LocationCountry> = {
  FR: {
    regionLabel: "Département",
    regions: [
      { name: "Ain (01)", cities: ["Bourg-en-Bresse", "Oyonnax", "Belley", "Ambérieu-en-Bugey", "Gex"] },
      { name: "Aisne (02)", cities: ["Saint-Quentin", "Laon", "Soissons", "Chauny", "Tergnier"] },
      { name: "Allier (03)", cities: ["Moulins", "Vichy", "Montluçon", "Cusset", "Yzeure"] },
      { name: "Alpes-de-Haute-Provence (04)", cities: ["Digne-les-Bains", "Manosque", "Sisteron", "Apt"] },
      { name: "Hautes-Alpes (05)", cities: ["Gap", "Briançon", "Embrun"] },
      { name: "Alpes-Maritimes (06)", cities: ["Nice", "Cannes", "Antibes", "Menton", "Grasse", "Cagnes-sur-Mer"] },
      { name: "Ardèche (07)", cities: ["Privas", "Annonay", "Aubenas", "Tournon-sur-Rhône"] },
      { name: "Ardennes (08)", cities: ["Charleville-Mézières", "Sedan", "Revin", "Givet"] },
      { name: "Ariège (09)", cities: ["Foix", "Pamiers", "Saint-Girons"] },
      { name: "Aube (10)", cities: ["Troyes", "Bar-sur-Aube", "Nogent-sur-Seine", "Romilly-sur-Seine"] },
      { name: "Aude (11)", cities: ["Carcassonne", "Narbonne", "Castelnaudary", "Limoux"] },
      { name: "Aveyron (12)", cities: ["Rodez", "Millau", "Villefranche-de-Rouergue", "Decazeville"] },
      { name: "Bouches-du-Rhône (13)", cities: ["Marseille", "Aix-en-Provence", "Arles", "Aubagne", "Martigues", "Istres", "Salon-de-Provence"] },
      { name: "Calvados (14)", cities: ["Caen", "Bayeux", "Lisieux", "Hérouville-Saint-Clair", "Vire"] },
      { name: "Cantal (15)", cities: ["Aurillac", "Mauriac", "Saint-Flour"] },
      { name: "Charente (16)", cities: ["Angoulême", "Cognac", "Soyaux", "La Couronne"] },
      { name: "Charente-Maritime (17)", cities: ["La Rochelle", "Rochefort", "Saintes", "Royan", "Jonzac"] },
      { name: "Cher (18)", cities: ["Bourges", "Vierzon", "Saint-Amand-Montrond"] },
      { name: "Corrèze (19)", cities: ["Tulle", "Brive-la-Gaillarde", "Ussel"] },
      { name: "Corse-du-Sud (2A)", cities: ["Ajaccio", "Porto-Vecchio", "Sartène", "Propriano"] },
      { name: "Haute-Corse (2B)", cities: ["Bastia", "Corte", "Calvi", "L'Île-Rousse"] },
      { name: "Côte-d'Or (21)", cities: ["Dijon", "Beaune", "Chenôve", "Talant", "Longvic"] },
      { name: "Côtes-d'Armor (22)", cities: ["Saint-Brieuc", "Lannion", "Dinan", "Loudéac", "Guingamp"] },
      { name: "Creuse (23)", cities: ["Guéret", "Aubusson", "Bourganeuf"] },
      { name: "Dordogne (24)", cities: ["Périgueux", "Bergerac", "Sarlat-la-Canéda", "Ribérac"] },
      { name: "Doubs (25)", cities: ["Besançon", "Montbéliard", "Pontarlier", "Sochaux", "Valentigney"] },
      { name: "Drôme (26)", cities: ["Valence", "Romans-sur-Isère", "Montélimar", "Pierrelatte", "Crest"] },
      { name: "Eure (27)", cities: ["Évreux", "Vernon", "Louviers", "Bernay", "Gisors"] },
      { name: "Eure-et-Loir (28)", cities: ["Chartres", "Dreux", "Châteaudun", "Nogent-le-Rotrou"] },
      { name: "Finistère (29)", cities: ["Brest", "Quimper", "Quimperlé", "Morlaix", "Concarneau"] },
      { name: "Gard (30)", cities: ["Nîmes", "Alès", "Bagnols-sur-Cèze", "Uzès", "Le Vigan"] },
      { name: "Haute-Garonne (31)", cities: ["Toulouse", "Colomiers", "Blagnac", "Muret", "Tournefeuille", "Saint-Gaudens"] },
      { name: "Gers (32)", cities: ["Auch", "Condom", "Nogaro"] },
      { name: "Gironde (33)", cities: ["Bordeaux", "Mérignac", "Pessac", "Talence", "Libourne", "Arcachon"] },
      { name: "Hérault (34)", cities: ["Montpellier", "Béziers", "Sète", "Lunel", "Agde"] },
      { name: "Ille-et-Vilaine (35)", cities: ["Rennes", "Saint-Malo", "Fougères", "Vitré", "Cesson-Sévigné"] },
      { name: "Indre (36)", cities: ["Châteauroux", "Issoudun", "Le Blanc"] },
      { name: "Indre-et-Loire (37)", cities: ["Tours", "Saint-Pierre-des-Corps", "Joué-lès-Tours", "Amboise"] },
      { name: "Isère (38)", cities: ["Grenoble", "Vienne", "Bourgoin-Jallieu", "Échirolles", "Voiron"] },
      { name: "Jura (39)", cities: ["Lons-le-Saunier", "Dole", "Saint-Claude", "Champagnole"] },
      { name: "Landes (40)", cities: ["Mont-de-Marsan", "Dax", "Biscarrosse", "Arcachon"] },
      { name: "Loir-et-Cher (41)", cities: ["Blois", "Vendôme", "Romorantin-Lanthenay", "Vineuil"] },
      { name: "Loire (42)", cities: ["Saint-Étienne", "Roanne", "Firminy", "Saint-Chamond"] },
      { name: "Haute-Loire (43)", cities: ["Le Puy-en-Velay", "Brioude", "Yssingeaux"] },
      { name: "Loire-Atlantique (44)", cities: ["Nantes", "Saint-Nazaire", "Saint-Herblain", "Rezé", "Orvault"] },
      { name: "Loiret (45)", cities: ["Orléans", "Saint-Jean-de-la-Ruelle", "Fleury-les-Aubrais", "Montargis"] },
      { name: "Lot (46)", cities: ["Cahors", "Figeac", "Gourdon"] },
      { name: "Lot-et-Garonne (47)", cities: ["Agen", "Marmande", "Villeneuve-sur-Lot", "Nérac"] },
      { name: "Lozère (48)", cities: ["Mende", "Florac", "Marvejols"] },
      { name: "Maine-et-Loire (49)", cities: ["Angers", "Cholet", "Saint-Barthélemy-d'Anjou", "Saumur"] },
      { name: "Manche (50)", cities: ["Cherbourg-en-Cotentin", "Saint-Lô", "Granville", "Avranches"] },
      { name: "Marne (51)", cities: ["Reims", "Châlons-en-Champagne", "Épernay", "Vitry-le-François"] },
      { name: "Haute-Marne (52)", cities: ["Chaumont", "Saint-Dizier", "Langres"] },
      { name: "Mayenne (53)", cities: ["Laval", "Mayenne", "Château-Gontier"] },
      { name: "Meurthe-et-Moselle (54)", cities: ["Nancy", "Vandœuvre-lès-Nancy", "Lunéville", "Pont-à-Mousson"] },
      { name: "Meuse (55)", cities: ["Bar-le-Duc", "Verdun", "Commercy"] },
      { name: "Morbihan (56)", cities: ["Vannes", "Lorient", "Pontivy", "Quiberon"] },
      { name: "Moselle (57)", cities: ["Metz", "Thionville", "Forbach", "Sarrebourg", "Sarreguemines"] },
      { name: "Nièvre (58)", cities: ["Nevers", "Cosne-Cours-sur-Loire", "Decize"] },
      { name: "Nord (59)", cities: ["Lille", "Roubaix", "Tourcoing", "Dunkerque", "Valenciennes", "Douai"] },
      { name: "Oise (60)", cities: ["Beauvais", "Compiègne", "Creil", "Senlis", "Noyon"] },
      { name: "Orne (61)", cities: ["Alençon", "Flers", "Argentan", "L'Aigle"] },
      { name: "Pas-de-Calais (62)", cities: ["Arras", "Boulogne-sur-Mer", "Calais", "Lens", "Béthune", "Liévin"] },
      { name: "Puy-de-Dôme (63)", cities: ["Clermont-Ferrand", "Riom", "Issoire", "Thiers", "Ambert"] },
      { name: "Pyrénées-Atlantiques (64)", cities: ["Pau", "Bayonne", "Anglet", "Biarritz", "Orthez"] },
      { name: "Hautes-Pyrénées (65)", cities: ["Tarbes", "Lourdes", "Bagnères-de-Bigorre"] },
      { name: "Pyrénées-Orientales (66)", cities: ["Perpignan", "Canet-en-Roussillon", "Saint-Estève"] },
      { name: "Bas-Rhin (67)", cities: ["Strasbourg", "Haguenau", "Schiltigheim", "Illkirch-Graffenstaden"] },
      { name: "Haut-Rhin (68)", cities: ["Mulhouse", "Colmar", "Saint-Louis", "Illzach"] },
      { name: "Rhône (69)", cities: ["Lyon", "Villeurbanne", "Vénissieux", "Caluire-et-Cuire", "Bron", "Saint-Priest"] },
      { name: "Haute-Saône (70)", cities: ["Vesoul", "Gray", "Lure"] },
      { name: "Saône-et-Loire (71)", cities: ["Mâcon", "Chalon-sur-Saône", "Montceau-les-Mines", "Le Creusot"] },
      { name: "Sarthe (72)", cities: ["Le Mans", "La Flèche", "Allonnes", "Sablé-sur-Sarthe"] },
      { name: "Savoie (73)", cities: ["Chambéry", "Aix-les-Bains", "Albertville", "Moûtiers"] },
      { name: "Haute-Savoie (74)", cities: ["Annecy", "Thonon-les-Bains", "Annemasse", "Cluses", "Bonneville"] },
      { name: "Paris (75)", cities: ["Paris"] },
      { name: "Seine-Maritime (76)", cities: ["Rouen", "Le Havre", "Dieppe", "Saint-Étienne-du-Rouvray", "Fécamp"] },
      { name: "Seine-et-Marne (77)", cities: ["Meaux", "Chelles", "Melun", "Pontault-Combault", "Savigny-le-Temple"] },
      { name: "Yvelines (78)", cities: ["Versailles", "Mantes-la-Jolie", "Saint-Quentin-en-Yvelines", "Rambouillet"] },
      { name: "Deux-Sèvres (79)", cities: ["Niort", "Bressuire", "Thouars"] },
      { name: "Somme (80)", cities: ["Amiens", "Abbeville", "Péronne"] },
      { name: "Tarn (81)", cities: ["Albi", "Castres", "Gaillac"] },
      { name: "Tarn-et-Garonne (82)", cities: ["Montauban", "Moissac", "Castelsarrasin"] },
      { name: "Var (83)", cities: ["Toulon", "Fréjus", "La Seyne-sur-Mer", "Hyères", "Draguignan"] },
      { name: "Vaucluse (84)", cities: ["Avignon", "Orange", "Carpentras", "Apt", "Cavaillon"] },
      { name: "Vendée (85)", cities: ["La Roche-sur-Yon", "Les Sables-d'Olonne", "Challans", "Saint-Jean-de-Monts"] },
      { name: "Vienne (86)", cities: ["Poitiers", "Châtellerault", "Loudun"] },
      { name: "Haute-Vienne (87)", cities: ["Limoges", "Saint-Junien", "Rochechouart"] },
      { name: "Vosges (88)", cities: ["Épinal", "Saint-Dié-des-Vosges", "Remiremont"] },
      { name: "Yonne (89)", cities: ["Auxerre", "Sens", "Avallon", "Joigny"] },
      { name: "Territoire de Belfort (90)", cities: ["Belfort", "Delle", "Valdoie"] },
      { name: "Essonne (91)", cities: ["Évry-Courcouronnes", "Corbeil-Essonnes", "Palaiseau", "Massy", "Longjumeau"] },
      { name: "Hauts-de-Seine (92)", cities: ["Boulogne-Billancourt", "Nanterre", "Colombes", "Issy-les-Moulineaux", "Rueil-Malmaison"] },
      { name: "Seine-Saint-Denis (93)", cities: ["Saint-Denis", "Montreuil", "Aubervilliers", "Aulnay-sous-Bois", "Bondy"] },
      { name: "Val-de-Marne (94)", cities: ["Créteil", "Vitry-sur-Seine", "Champigny-sur-Marne", "Saint-Maur-des-Fossés"] },
      { name: "Val-d'Oise (95)", cities: ["Cergy", "Argenteuil", "Sarcelles", "Gonesse"] },
      { name: "Guadeloupe (971)", cities: ["Pointe-à-Pitre", "Basse-Terre", "Le Gosier", "Sainte-Anne", "Les Abymes"] },
      { name: "Martinique (972)", cities: ["Fort-de-France", "Le Lamentin", "Saint-Joseph", "Le Robert"] },
      { name: "Guyane (973)", cities: ["Cayenne", "Saint-Laurent-du-Maroni", "Kourou", "Matoury"] },
      { name: "La Réunion (974)", cities: ["Saint-Denis", "Saint-Paul", "Le Tampon", "Saint-Pierre", "Saint-André"] },
      { name: "Mayotte (976)", cities: ["Mamoudzou", "Koungou", "Bandraboua", "Bandraboua"] },
    ],
  },

  BE: {
    regionLabel: "Province",
    regions: [
      { name: "Bruxelles", cities: ["Bruxelles", "Anderlecht", "Schaerbeek", "Molenbeek", "Ixelles"] },
      { name: "Hainaut", cities: ["Charleroi", "Mons", "Tournai", "La Louvière", "Mouscron"] },
      { name: "Liège", cities: ["Liège", "Seraing", "Herstal", "Verviers", "Visé"] },
      { name: "Namur", cities: ["Namur", "Dinant", "Gembloux", "Philippeville"] },
      { name: "Luxembourg", cities: ["Arlon", "Bastogne", "Marche-en-Famenne", "Virton"] },
      { name: "Brabant wallon", cities: ["Wavre", "Ottignies", "Nivelles", "Tubize"] },
      { name: "Anvers", cities: ["Anvers", "Malines", "Turnhout", "Lier"] },
      { name: "Flandre Orientale", cities: ["Gand", "Saint-Nicolas", "Alost", "Lokeren"] },
      { name: "Flandre Occidentale", cities: ["Bruges", "Courtrai", "Ostende", "Roulers"] },
      { name: "Brabant flamand", cities: ["Louvain", "Vilvorde", "Hal", "Diest"] },
      { name: "Limbourg", cities: ["Hasselt", "Genk", "Saint-Trond", "Tongres"] },
    ],
  },

  CH: {
    regionLabel: "Canton",
    regions: [
      { name: "Genève", cities: ["Genève", "Carouge", "Lancy", "Vernier", "Meyrin"] },
      { name: "Vaud", cities: ["Lausanne", "Yverdon-les-Bains", "Montreux", "Renens", "Nyon"] },
      { name: "Valais", cities: ["Sion", "Martigny", "Sierre", "Viège", "Brigue"] },
      { name: "Fribourg", cities: ["Fribourg", "Bulle", "Morat", "Romont"] },
      { name: "Neuchâtel", cities: ["Neuchâtel", "La Chaux-de-Fonds", "Le Locle"] },
      { name: "Jura", cities: ["Delémont", "Porrentruy", "Saignelégier"] },
      { name: "Zurich", cities: ["Zurich", "Winterthour", "Uster", "Dietikon"] },
      { name: "Berne", cities: ["Berne", "Bienne", "Thoune", "Köniz"] },
      { name: "Bâle-Ville", cities: ["Bâle", "Bettingen", "Riehen"] },
      { name: "Bâle-Campagne", cities: ["Liestal", "Allschwil", "Reinach"] },
      { name: "Tessin", cities: ["Lugano", "Bellinzone", "Locarno", "Mendrisio"] },
      { name: "Argovie", cities: ["Aarau", "Baden", "Wettingen"] },
    ],
  },

  CA: {
    regionLabel: "Province",
    regions: [
      { name: "Québec", cities: ["Montréal", "Québec", "Laval", "Gatineau", "Longueuil", "Sherbrooke", "Saguenay"] },
      { name: "Ontario", cities: ["Toronto", "Ottawa", "Mississauga", "Hamilton", "Brampton", "London"] },
      { name: "Colombie-Britannique", cities: ["Vancouver", "Victoria", "Surrey", "Burnaby", "Kelowna"] },
      { name: "Alberta", cities: ["Calgary", "Edmonton", "Lethbridge", "Red Deer"] },
      { name: "Nouvelle-Écosse", cities: ["Halifax", "Dartmouth", "Sydney"] },
      { name: "Nouveau-Brunswick", cities: ["Moncton", "Fredericton", "Saint John"] },
      { name: "Manitoba", cities: ["Winnipeg", "Brandon", "Steinbach"] },
      { name: "Saskatchewan", cities: ["Saskatoon", "Regina", "Moose Jaw"] },
    ],
  },

  MA: {
    regionLabel: "Région",
    regions: [
      { name: "Casablanca-Settat", cities: ["Casablanca", "Mohammedia", "Settat", "El Jadida", "Berrechid"] },
      { name: "Rabat-Salé-Kénitra", cities: ["Rabat", "Salé", "Kénitra", "Témara", "Khémisset"] },
      { name: "Fès-Meknès", cities: ["Fès", "Meknès", "Taza", "Sefrou", "Ifrane"] },
      { name: "Marrakech-Safi", cities: ["Marrakech", "Safi", "Essaouira", "Ben Guerir"] },
      { name: "Souss-Massa", cities: ["Agadir", "Inezgane", "Taroudant", "Tiznit"] },
      { name: "Tanger-Tétouan-Al Hoceïma", cities: ["Tanger", "Tétouan", "Al Hoceïma", "Larache", "Asilah"] },
      { name: "L'Oriental", cities: ["Oujda", "Nador", "Berkane", "Taourirt"] },
      { name: "Béni Mellal-Khénifra", cities: ["Béni Mellal", "Khouribga", "Fquih Ben Salah"] },
      { name: "Drâa-Tafilalet", cities: ["Errachidia", "Ouarzazate", "Zagora", "Tinghir"] },
      { name: "Laâyoune-Sakia El Hamra", cities: ["Laâyoune", "Boujdour", "Es-Smara"] },
    ],
  },

  DZ: {
    regionLabel: "Wilaya",
    regions: [
      { name: "Alger", cities: ["Alger", "Bab Ezzouar", "Dar El Beïda", "Kouba", "Hussein Dey"] },
      { name: "Oran", cities: ["Oran", "Es Senia", "Aïn Témouchent", "Arzew"] },
      { name: "Constantine", cities: ["Constantine", "El Khroub", "Aïn Smara", "Didouche Mourad"] },
      { name: "Annaba", cities: ["Annaba", "El Bouni", "El Hadjar", "Aïn Berda"] },
      { name: "Sétif", cities: ["Sétif", "El Eulma", "Aïn Oulmène"] },
      { name: "Blida", cities: ["Blida", "Boufarik", "Larbaa", "Meftah"] },
      { name: "Tizi Ouzou", cities: ["Tizi Ouzou", "Azazga", "Draa Ben Khedda"] },
      { name: "Béjaïa", cities: ["Béjaïa", "Akbou", "Tazmalt", "Kherrata"] },
      { name: "Tlemcen", cities: ["Tlemcen", "Maghnia", "Nedroma", "Ghazaouet"] },
      { name: "Batna", cities: ["Batna", "Barika", "Aïn Touta", "Merouana"] },
      { name: "Biskra", cities: ["Biskra", "Tolga", "Ouled Djellal"] },
      { name: "Médéa", cities: ["Médéa", "Berrouaghia", "Khemis Miliana"] },
    ],
  },

  TN: {
    regionLabel: "Gouvernorat",
    regions: [
      { name: "Tunis", cities: ["Tunis", "Ariana", "Ben Arous", "La Marsa", "La Goulette"] },
      { name: "Sfax", cities: ["Sfax", "Sakiet Ezzit", "Sakiet Eddaïer", "El Ain"] },
      { name: "Sousse", cities: ["Sousse", "Monastir", "Mahdia", "Enfidha"] },
      { name: "Bizerte", cities: ["Bizerte", "Menzel Bourguiba", "Mateur", "Sejnane"] },
      { name: "Kairouan", cities: ["Kairouan", "Sbikha", "Haffouz"] },
      { name: "Nabeul", cities: ["Nabeul", "Hammamet", "Kelibia", "Grombalia"] },
      { name: "Jendouba", cities: ["Jendouba", "Tabarka", "Aïn Draham"] },
      { name: "Gafsa", cities: ["Gafsa", "Métlaoui", "Redeyef"] },
      { name: "Gabès", cities: ["Gabès", "Djerba", "Zarzis", "Medenine"] },
      { name: "Kasserine", cities: ["Kasserine", "Feriana", "Sbeitla"] },
    ],
  },

  SN: {
    regionLabel: "Région",
    regions: [
      { name: "Dakar", cities: ["Dakar", "Pikine", "Guédiawaye", "Rufisque", "Bargny"] },
      { name: "Thiès", cities: ["Thiès", "Mbour", "Tivaouane", "Saly"] },
      { name: "Saint-Louis", cities: ["Saint-Louis", "Richard-Toll", "Podor", "Dagana"] },
      { name: "Diourbel", cities: ["Diourbel", "Mbacké", "Touba", "Bambey"] },
      { name: "Kaolack", cities: ["Kaolack", "Guinguinéo", "Nioro du Rip"] },
      { name: "Ziguinchor", cities: ["Ziguinchor", "Bignona", "Oussouye"] },
      { name: "Tambacounda", cities: ["Tambacounda", "Bakel", "Kédougou"] },
    ],
  },

  CI: {
    regionLabel: "District",
    regions: [
      { name: "Abidjan", cities: ["Abidjan", "Abobo", "Adjamé", "Koumassi", "Yopougon"] },
      { name: "Bas-Sassandra", cities: ["San-Pédro", "Sassandra", "Tabou"] },
      { name: "Comoé", cities: ["Abengourou", "Agnibilékrou", "Bettié"] },
      { name: "Denguélé", cities: ["Odienné", "Minignan"] },
      { name: "Gôh-Djiboua", cities: ["Gagnoa", "Divo", "Lakota"] },
      { name: "Lacs", cities: ["Yamoussoukro", "Dimbokro", "Toumodi"] },
      { name: "Lagunes", cities: ["Grand-Bassam", "Jacqueville", "Dabou"] },
      { name: "Montagnes", cities: ["Man", "Danané", "Guiglo"] },
      { name: "Sassandra-Marahoué", cities: ["Daloa", "Issia", "Vavoua"] },
      { name: "Savanes", cities: ["Korhogo", "Ferkessédougou", "Tengréla"] },
      { name: "Vallée du Bandama", cities: ["Bouaké", "Sakassou", "Béoumi"] },
      { name: "Woroba", cities: ["Séguéla", "Touba", "Kani"] },
      { name: "Zanzan", cities: ["Bondoukou", "Tanda", "Bouna"] },
    ],
  },

  GB: {
    regionLabel: "Région",
    regions: [
      { name: "Angleterre — Grand Londres", cities: ["Londres", "Westminster", "Camden", "Hackney", "Southwark"] },
      { name: "Angleterre — Nord-Ouest", cities: ["Manchester", "Liverpool", "Salford", "Bolton", "Blackpool"] },
      { name: "Angleterre — Midlands", cities: ["Birmingham", "Coventry", "Leicester", "Nottingham", "Derby"] },
      { name: "Angleterre — Yorkshire", cities: ["Leeds", "Sheffield", "Bradford", "Hull"] },
      { name: "Angleterre — Sud-Est", cities: ["Brighton", "Southampton", "Oxford", "Reading"] },
      { name: "Écosse", cities: ["Édimbourg", "Glasgow", "Aberdeen", "Dundee", "Inverness"] },
      { name: "Pays de Galles", cities: ["Cardiff", "Swansea", "Newport", "Bangor"] },
      { name: "Irlande du Nord", cities: ["Belfast", "Derry", "Lisburn"] },
    ],
  },

  DE: {
    regionLabel: "Land",
    regions: [
      { name: "Berlin", cities: ["Berlin"] },
      { name: "Bavière", cities: ["Munich", "Nuremberg", "Augsbourg", "Ratisbonne", "Ingolstadt"] },
      { name: "Rhénanie-du-Nord-Westphalie", cities: ["Cologne", "Düsseldorf", "Dortmund", "Essen", "Duisbourg"] },
      { name: "Bade-Wurtemberg", cities: ["Stuttgart", "Karlsruhe", "Mannheim", "Heidelberg", "Fribourg"] },
      { name: "Hambourg", cities: ["Hambourg"] },
      { name: "Saxe", cities: ["Leipzig", "Dresde", "Chemnitz"] },
      { name: "Hesse", cities: ["Francfort", "Wiesbaden", "Kassel", "Darmstadt"] },
      { name: "Rhénanie-Palatinat", cities: ["Mayence", "Ludwigshafen", "Trèves", "Kaiserslautern"] },
    ],
  },

  ES: {
    regionLabel: "Communauté autonome",
    regions: [
      { name: "Madrid", cities: ["Madrid", "Alcalá de Henares", "Getafe", "Móstoles", "Leganés"] },
      { name: "Catalogne", cities: ["Barcelone", "Tarragone", "Gérone", "Lleida", "Mataró"] },
      { name: "Andalousie", cities: ["Séville", "Málaga", "Grenade", "Cordoue", "Almería"] },
      { name: "Pays Basque", cities: ["Bilbao", "Saint-Sébastien", "Vitoria-Gasteiz", "Barakaldo"] },
      { name: "Communauté valencienne", cities: ["Valence", "Alicante", "Elche", "Castellón"] },
      { name: "Galice", cities: ["Vigo", "La Corogne", "Saint-Jacques-de-Compostelle", "Pontevedra"] },
      { name: "Aragon", cities: ["Saragosse", "Huesca", "Teruel"] },
      { name: "Castille-et-León", cities: ["Valladolid", "Burgos", "Salamanque", "León"] },
      { name: "Îles Canaries", cities: ["Las Palmas", "Santa Cruz de Tenerife"] },
      { name: "Îles Baléares", cities: ["Palma de Majorque", "Mahón", "Ibiza"] },
    ],
  },

  IT: {
    regionLabel: "Région",
    regions: [
      { name: "Latium", cities: ["Rome", "Latina", "Frosinone", "Viterbe"] },
      { name: "Lombardie", cities: ["Milan", "Bergame", "Brescia", "Monza", "Côme"] },
      { name: "Campanie", cities: ["Naples", "Salerne", "Caserte", "Pozzuoli"] },
      { name: "Sicile", cities: ["Palerme", "Catane", "Messine", "Syracuse"] },
      { name: "Vénétie", cities: ["Venise", "Vérone", "Padoue", "Trévise", "Vicence"] },
      { name: "Piémont", cities: ["Turin", "Alessandria", "Novare", "Asti"] },
      { name: "Toscane", cities: ["Florence", "Sienne", "Pise", "Livourne", "Arezzo"] },
      { name: "Émilie-Romagne", cities: ["Bologne", "Modène", "Parme", "Ferrare", "Rimini"] },
      { name: "Ligurie", cities: ["Gênes", "La Spezia", "Savone"] },
      { name: "Sardaigne", cities: ["Cagliari", "Sassari", "Olbia"] },
    ],
  },

  PT: {
    regionLabel: "District",
    regions: [
      { name: "Lisbonne", cities: ["Lisbonne", "Sintra", "Cascais", "Amadora", "Odivelas", "Loures"] },
      { name: "Porto", cities: ["Porto", "Vila Nova de Gaia", "Matosinhos", "Braga", "Guimarães"] },
      { name: "Faro", cities: ["Faro", "Portimão", "Lagos", "Tavira", "Albufeira"] },
      { name: "Setúbal", cities: ["Setúbal", "Almada", "Barreiro", "Seixal"] },
      { name: "Aveiro", cities: ["Aveiro", "Santa Maria da Feira", "Oliveira de Azeméis"] },
      { name: "Coimbra", cities: ["Coimbra", "Figueira da Foz", "Cantanhede"] },
      { name: "Braga", cities: ["Braga", "Guimarães", "Barcelos", "Famalicão"] },
    ],
  },

  NL: {
    regionLabel: "Province",
    regions: [
      { name: "Hollande-Septentrionale", cities: ["Amsterdam", "Haarlem", "Alkmaar", "Zaandam"] },
      { name: "Hollande-Méridionale", cities: ["Rotterdam", "La Haye", "Delft", "Leiden", "Dordrecht"] },
      { name: "Utrecht", cities: ["Utrecht", "Amersfoort", "Nieuwegein"] },
      { name: "Brabant-Septentrional", cities: ["Eindhoven", "Bréda", "Tilbourg", "Bois-le-Duc"] },
      { name: "Gueldre", cities: ["Arnhem", "Nimègue", "Apeldoorn"] },
      { name: "Frise", cities: ["Leeuwarden", "Sneek", "Heerenveen"] },
    ],
  },

  LU: {
    regionLabel: "Canton",
    regions: [
      { name: "Luxembourg", cities: ["Luxembourg", "Bertrange", "Hesperange", "Strassen"] },
      { name: "Esch-sur-Alzette", cities: ["Esch-sur-Alzette", "Differdange", "Sanem"] },
      { name: "Capellen", cities: ["Mamer", "Steinfort", "Kehlen"] },
      { name: "Mersch", cities: ["Mersch", "Lintgen", "Lorentzweiler"] },
      { name: "Grevenmacher", cities: ["Grevenmacher", "Mertert"] },
      { name: "Remich", cities: ["Remich", "Mondorf-les-Bains"] },
      { name: "Diekirch", cities: ["Diekirch", "Ettelbruck"] },
      { name: "Clervaux", cities: ["Clervaux", "Wiltz"] },
    ],
  },

  US: {
    regionLabel: "État",
    regions: [
      { name: "Californie", cities: ["Los Angeles", "San Francisco", "San Diego", "San José", "Sacramento"] },
      { name: "New York", cities: ["New York City", "Buffalo", "Rochester", "Albany"] },
      { name: "Texas", cities: ["Houston", "Dallas", "Austin", "San Antonio", "El Paso"] },
      { name: "Floride", cities: ["Miami", "Orlando", "Tampa", "Jacksonville", "Fort Lauderdale"] },
      { name: "Illinois", cities: ["Chicago", "Springfield", "Aurora", "Rockford"] },
      { name: "Washington", cities: ["Seattle", "Spokane", "Tacoma", "Bellevue"] },
      { name: "Louisiane", cities: ["La Nouvelle-Orléans", "Baton Rouge", "Shreveport"] },
    ],
  },

  BR: {
    regionLabel: "État",
    regions: [
      { name: "São Paulo", cities: ["São Paulo", "Guarulhos", "Campinas", "São Bernardo", "Osasco"] },
      { name: "Rio de Janeiro", cities: ["Rio de Janeiro", "Niterói", "Nova Iguaçu", "Duque de Caxias"] },
      { name: "Bahia", cities: ["Salvador", "Feira de Santana", "Vitória da Conquista"] },
      { name: "Minas Gerais", cities: ["Belo Horizonte", "Uberlândia", "Contagem", "Juiz de Fora"] },
      { name: "Paraná", cities: ["Curitiba", "Londrina", "Maringá", "Foz do Iguaçu"] },
      { name: "Rio Grande do Sul", cities: ["Porto Alegre", "Caxias do Sul", "Pelotas"] },
      { name: "Pernambuco", cities: ["Recife", "Olinda", "Caruaru"] },
    ],
  },

  MX: {
    regionLabel: "État",
    regions: [
      { name: "Mexico (CDMX)", cities: ["Mexico", "Gustavo A. Madero", "Iztapalapa", "Coyoacán"] },
      { name: "Jalisco", cities: ["Guadalajara", "Zapopan", "Tlaquepaque"] },
      { name: "Nuevo León", cities: ["Monterrey", "San Nicolás", "Guadalupe", "Apodaca"] },
      { name: "Puebla", cities: ["Puebla", "Tehuacán", "Cholula"] },
      { name: "Guanajuato", cities: ["León", "Irapuato", "Celaya", "Guanajuato"] },
    ],
  },

  JP: {
    regionLabel: "Préfecture",
    regions: [
      { name: "Tokyo", cities: ["Tokyo", "Shinjuku", "Shibuya", "Setagaya"] },
      { name: "Osaka", cities: ["Osaka", "Sakai", "Higashiosaka"] },
      { name: "Kanagawa", cities: ["Yokohama", "Kawasaki", "Sagamihara"] },
      { name: "Aichi", cities: ["Nagoya", "Toyota", "Okazaki"] },
      { name: "Hokkaido", cities: ["Sapporo", "Asahikawa", "Hakodate"] },
      { name: "Fukuoka", cities: ["Fukuoka", "Kitakyushu", "Kurume"] },
    ],
  },

  AU: {
    regionLabel: "État",
    regions: [
      { name: "Nouvelle-Galles du Sud", cities: ["Sydney", "Newcastle", "Wollongong", "Parramatta"] },
      { name: "Victoria", cities: ["Melbourne", "Geelong", "Ballarat", "Bendigo"] },
      { name: "Queensland", cities: ["Brisbane", "Gold Coast", "Sunshine Coast", "Townsville"] },
      { name: "Australie-Occidentale", cities: ["Perth", "Fremantle", "Mandurah"] },
      { name: "Australie-Méridionale", cities: ["Adélaïde", "Mount Gambier"] },
    ],
  },

  OTHER: {
    regionLabel: "Région",
    regions: [
      { name: "Autre", cities: ["Autre ville"] },
    ],
  },
};
